# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7de3358c75d7f83196bb9ec434f8325a7ffc4d93330a47b3a21921d3f4e082015d3a07ea96013b5a5d1103fb4f02674d540284f683a12638385a1b94e1cd7d73

test:
  secret_key_base: 78859385353e16f5a0a119b68674abf3b197f0400c00cfb4591aaa9cf95ba00b6f82f56f5beffa5b670476e61d35515776b9189c4f0003784d1376f8564a7f55

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
